name: personal_finance
version: "0.1.0"
config-version: 2
profile: personal_finance
model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]
models:
  personal_finance:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

